[project]
name = "using-vidgear"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python>=4.10.0.84",
    "pyvirtualcam>=0.12.0",
]
